import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
};

export const organizations = sqliteTable(
  "organizations",
  {
    id: text("id").primaryKey(),
    code: text("code").notNull(),
    name: text("name").notNull(),
    shortName: text("short_name"),
    level: text("level").notNull().default("đơn vị"),
    parentId: text("parent_id"),
    managerPersonId: text("manager_person_id"),
    status: text("status").notNull().default("active"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_organizations_code").on(table.code),
    index("idx_organizations_parent").on(table.parentId),
    index("idx_organizations_status").on(table.status),
  ],
);

export const people = sqliteTable(
  "people",
  {
    id: text("id").primaryKey(),
    staffCode: text("staff_code"),
    lecturerCode: text("lecturer_code"),
    personType: text("person_type").notNull().default("Viên chức"),
    fullName: text("full_name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    birthDate: text("birth_date"),
    gender: text("gender"),
    organizationId: text("organization_id").references(() => organizations.id),
    organizationNameSource: text("organization_name_source"),
    department: text("department"),
    position: text("position"),
    professionalTitle: text("professional_title"),
    employmentStatus: text("employment_status").notNull().default("đang công tác"),
    startDate: text("start_date"),
    phone: text("phone"),
    workEmail: text("work_email"),
    personalEmail: text("personal_email"),
    identityNumber: text("identity_number"),
    taxCode: text("tax_code"),
    socialInsuranceNumber: text("social_insurance_number"),
    homeTown: text("home_town"),
    address: text("address"),
    specialization: text("specialization"),
    workArrangement: text("work_arrangement"),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    sourceIdentityKey: text("source_identity_key"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    updatedBy: text("updated_by"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_people_staff_code").on(table.staffCode),
    uniqueIndex("uq_people_lecturer_code").on(table.lecturerCode),
    uniqueIndex("uq_people_work_email").on(table.workEmail),
    index("idx_people_name_birth").on(table.normalizedName, table.birthDate),
    index("idx_people_phone").on(table.phone),
    index("idx_people_source_identity").on(table.sourceIdentityKey),
    index("idx_people_organization").on(table.organizationId),
    index("idx_people_status").on(table.employmentStatus),
    index("idx_people_sync_state").on(table.syncState),
  ],
);

export const qualifications = sqliteTable(
  "qualifications",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").notNull().references(() => people.id),
    academicTitle: text("academic_title"),
    degreeLevel: text("degree_level"),
    degreeYear: integer("degree_year"),
    major: text("major"),
    disciplineGroup: text("discipline_group"),
    institution: text("institution"),
    country: text("country"),
    graduationYear: integer("graduation_year"),
    foreignLanguage: text("foreign_language"),
    informatics: text("informatics"),
    phdStatus: text("phd_status"),
    startDate: text("start_date"),
    endDate: text("end_date"),
    notes: text("notes"),
    educationHistoryJson: text("education_history_json"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_qualifications_person").on(table.personId),
    index("idx_qualifications_level").on(table.degreeLevel),
  ],
);

export const trainingRecords = sqliteTable(
  "training_records",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").notNull().references(() => people.id),
    trainingType: text("training_type").notNull(),
    programName: text("program_name"),
    degreeLevel: text("degree_level"),
    major: text("major"),
    disciplineGroup: text("discipline_group"),
    institution: text("institution"),
    country: text("country"),
    countryScope: text("country_scope"),
    fundingSource: text("funding_source"),
    status: text("status").notNull().default("chờ xác minh"),
    startDate: text("start_date"),
    endDate: text("end_date"),
    decisionNumber: text("decision_number"),
    foreignLanguage: text("foreign_language"),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_training_records_person").on(table.personId, table.status),
    index("idx_training_records_due").on(table.status, table.endDate),
  ],
);

export const trainingCommitments = sqliteTable(
  "training_commitments",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").notNull().references(() => people.id),
    trainingRecordId: text("training_record_id").references(() => trainingRecords.id),
    decisionNumber: text("decision_number"),
    amount: integer("amount"),
    startDate: text("start_date"),
    dueDate: text("due_date"),
    status: text("status").notNull().default("chờ xác minh"),
    completedDate: text("completed_date"),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_training_commitments_person").on(table.personId, table.status),
    index("idx_training_commitments_due").on(table.status, table.dueDate),
  ],
);

export const documentRecords = sqliteTable(
  "document_records",
  {
    id: text("id").primaryKey(),
    ownerEntityType: text("owner_entity_type").notNull(),
    ownerEntityId: text("owner_entity_id").notNull(),
    fileType: text("file_type").notNull(),
    fileName: text("file_name").notNull(),
    documentNumber: text("document_number"),
    documentDate: text("document_date"),
    documentVersion: integer("document_version").notNull().default(1),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_document_records_owner").on(table.ownerEntityType, table.ownerEntityId),
    index("idx_document_records_number").on(table.documentNumber),
  ],
);

export const personAssignments = sqliteTable(
  "person_assignments",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").notNull().references(() => people.id),
    organizationId: text("organization_id").references(() => organizations.id),
    assignmentType: text("assignment_type").notNull(),
    title: text("title").notNull(),
    startDate: text("start_date"),
    endDate: text("end_date"),
    status: text("status").notNull().default("active"),
    decisionNumber: text("decision_number"),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_person_assignments_person").on(table.personId, table.status),
    index("idx_person_assignments_org").on(table.organizationId),
  ],
);

export const employmentEvents = sqliteTable(
  "employment_events",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").notNull().references(() => people.id),
    eventType: text("event_type").notNull(),
    fromOrganizationId: text("from_organization_id").references(() => organizations.id),
    toOrganizationId: text("to_organization_id").references(() => organizations.id),
    oldValueJson: text("old_value_json"),
    newValueJson: text("new_value_json"),
    effectiveDate: text("effective_date").notNull(),
    decisionNumber: text("decision_number"),
    reason: text("reason"),
    evidenceFileId: text("evidence_file_id"),
    createdBy: text("created_by").notNull(),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_employment_events_person_date").on(table.personId, table.effectiveDate),
    index("idx_employment_events_type_date").on(table.eventType, table.effectiveDate),
  ],
);

export const organizationHistory = sqliteTable(
  "organization_history",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    changeType: text("change_type").notNull(),
    oldValueJson: text("old_value_json"),
    newValueJson: text("new_value_json"),
    effectiveDate: text("effective_date").notNull(),
    decisionNumber: text("decision_number"),
    notes: text("notes"),
    createdBy: text("created_by").notNull(),
    ...timestamps,
  },
  (table) => [index("idx_organization_history_org_date").on(table.organizationId, table.effectiveDate)],
);

export const contracts = sqliteTable(
  "contracts",
  {
    id: text("id").primaryKey(),
    personId: text("person_id").references(() => people.id),
    contractNumber: text("contract_number"),
    contractType: text("contract_type").notNull(),
    sourcePersonName: text("source_person_name").notNull(),
    sourceBirthDate: text("source_birth_date"),
    signer: text("signer"),
    signingOrganization: text("signing_organization"),
    usingOrganizationId: text("using_organization_id").references(() => organizations.id),
    usingOrganizationSource: text("using_organization_source"),
    roleOrSpecialty: text("role_or_specialty"),
    salaryCoefficient: text("salary_coefficient"),
    signedDate: text("signed_date"),
    effectiveDate: text("effective_date"),
    startDate: text("start_date"),
    endDate: text("end_date"),
    durationMonths: integer("duration_months"),
    periodText: text("period_text"),
    status: text("status").notNull().default("chờ bổ sung"),
    terminatedDate: text("terminated_date"),
    terminationReason: text("termination_reason"),
    notes: text("notes"),
    sourceFile: text("source_file"),
    sourceSheet: text("source_sheet"),
    sourceRow: integer("source_row"),
    sourceIdentityKey: text("source_identity_key").notNull(),
    rawData: text("raw_data"),
    checksum: text("checksum"),
    version: integer("version").notNull().default(1),
    syncState: text("sync_state").notNull().default("pending"),
    updatedBy: text("updated_by"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_contracts_source_identity").on(table.sourceIdentityKey),
    index("idx_contracts_number").on(table.contractNumber),
    index("idx_contracts_person").on(table.personId),
    index("idx_contracts_status_end").on(table.status, table.endDate),
    index("idx_contracts_type").on(table.contractType),
  ],
);

export const sourceImports = sqliteTable(
  "source_imports",
  {
    id: text("id").primaryKey(),
    fileName: text("file_name").notNull(),
    fileChecksum: text("file_checksum").notNull(),
    fileSize: integer("file_size"),
    sheetName: text("sheet_name"),
    headerRow: integer("header_row"),
    mappingVersion: text("mapping_version"),
    mode: text("mode").notNull(),
    status: text("status").notNull().default("validating"),
    totalRows: integer("total_rows").notNull().default(0),
    insertedRows: integer("inserted_rows").notNull().default(0),
    updatedRows: integer("updated_rows").notNull().default(0),
    duplicateRows: integer("duplicate_rows").notNull().default(0),
    skippedRows: integer("skipped_rows").notNull().default(0),
    errorRows: integer("error_rows").notNull().default(0),
    importedBy: text("imported_by").notNull(),
    completedAt: text("completed_at"),
    ...timestamps,
  },
  (table) => [
    index("idx_source_imports_checksum").on(table.fileChecksum),
    index("idx_source_imports_status").on(table.status),
  ],
);

export const importErrors = sqliteTable(
  "import_errors",
  {
    id: text("id").primaryKey(),
    importId: text("import_id").notNull().references(() => sourceImports.id),
    sheetName: text("sheet_name"),
    sourceRow: integer("source_row"),
    sourceColumn: text("source_column"),
    errorCode: text("error_code").notNull(),
    severity: text("severity").notNull(),
    sourceValue: text("source_value"),
    message: text("message").notNull(),
    suggestedFix: text("suggested_fix"),
    resolvedAt: text("resolved_at"),
    resolvedBy: text("resolved_by"),
    ...timestamps,
  },
  (table) => [index("idx_import_errors_import").on(table.importId, table.severity)],
);

export const mappingTemplates = sqliteTable(
  "mapping_templates",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    filePattern: text("file_pattern").notNull(),
    sheetPattern: text("sheet_pattern"),
    entityType: text("entity_type").notNull(),
    version: integer("version").notNull().default(1),
    headerRow: integer("header_row").notNull(),
    headerDepth: integer("header_depth").notNull().default(1),
    mappingJson: text("mapping_json").notNull(),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    ...timestamps,
  },
  (table) => [uniqueIndex("uq_mapping_templates_name_version").on(table.name, table.version)],
);

export const alerts = sqliteTable(
  "alerts",
  {
    id: text("id").primaryKey(),
    dedupKey: text("dedup_key").notNull(),
    severity: text("severity").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    title: text("title").notNull(),
    message: text("message").notNull(),
    organizationId: text("organization_id").references(() => organizations.id),
    dueDate: text("due_date"),
    assigneeUserId: text("assignee_user_id"),
    status: text("status").notNull().default("unread"),
    snoozedUntil: text("snoozed_until"),
    resolvedAt: text("resolved_at"),
    notes: text("notes"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_alerts_dedup_key").on(table.dedupKey),
    index("idx_alerts_status_due").on(table.status, table.dueDate),
    index("idx_alerts_org").on(table.organizationId),
  ],
);

export const fileRecords = sqliteTable(
  "file_records",
  {
    id: text("id").primaryKey(),
    ownerEntityType: text("owner_entity_type").notNull(),
    ownerEntityId: text("owner_entity_id").notNull(),
    storageKey: text("storage_key").notNull(),
    fileName: text("file_name").notNull(),
    contentType: text("content_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    checksum: text("checksum"),
    fileVersion: integer("file_version").notNull().default(1),
    replacesFileId: text("replaces_file_id"),
    uploadedBy: text("uploaded_by").notNull(),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_file_records_storage_key").on(table.storageKey),
    index("idx_file_records_owner").on(table.ownerEntityType, table.ownerEntityId),
  ],
);

export const positions = sqliteTable(
  "positions",
  {
    id: text("id").primaryKey(),
    code: text("code").notNull(),
    name: text("name").notNull(),
    positionType: text("position_type").notNull().default("Chức vụ"),
    organizationId: text("organization_id").references(() => organizations.id),
    description: text("description"),
    status: text("status").notNull().default("active"),
    deletedAt: text("deleted_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_positions_code").on(table.code),
    index("idx_positions_org_status").on(table.organizationId, table.status),
  ],
);

export const academicYears = sqliteTable(
  "academic_years",
  {
    id: text("id").primaryKey(),
    code: text("code").notNull(),
    name: text("name").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    isCurrent: integer("is_current", { mode: "boolean" }).notNull().default(false),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_academic_years_code").on(table.code),
    index("idx_academic_years_current").on(table.isCurrent),
  ],
);

export const systemSettings = sqliteTable(
  "system_settings",
  {
    key: text("key").primaryKey(),
    valueJson: text("value_json").notNull(),
    updatedBy: text("updated_by").notNull(),
    ...timestamps,
  },
  (table) => [index("idx_system_settings_updated").on(table.updatedAt)],
);

export const auditLogs = sqliteTable(
  "audit_logs",
  {
    id: text("id").primaryKey(),
    actorUserId: text("actor_user_id").notNull(),
    actorEmail: text("actor_email"),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    beforeJson: text("before_json"),
    afterJson: text("after_json"),
    changedFields: text("changed_fields"),
    reason: text("reason"),
    evidenceFileId: text("evidence_file_id"),
    requestId: text("request_id"),
    deviceSession: text("device_session"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_audit_entity").on(table.entityType, table.entityId),
    index("idx_audit_actor_date").on(table.actorUserId, table.createdAt),
  ],
);

export const idempotencyKeys = sqliteTable(
  "idempotency_keys",
  {
    key: text("key").primaryKey(),
    actorUserId: text("actor_user_id").notNull(),
    operation: text("operation").notNull(),
    resultJson: text("result_json"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [index("idx_idempotency_actor").on(table.actorUserId, table.createdAt)],
);

export const syncConflicts = sqliteTable(
  "sync_conflicts",
  {
    id: text("id").primaryKey(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    baseVersion: integer("base_version").notNull(),
    serverVersion: integer("server_version").notNull(),
    localJson: text("local_json").notNull(),
    serverJson: text("server_json").notNull(),
    status: text("status").notNull().default("open"),
    resolvedBy: text("resolved_by"),
    resolution: text("resolution"),
    resolvedAt: text("resolved_at"),
    ...timestamps,
  },
  (table) => [index("idx_sync_conflicts_status").on(table.status, table.entityType)],
);

export const snapshots = sqliteTable(
  "snapshots",
  {
    id: text("id").primaryKey(),
    periodYear: integer("period_year").notNull(),
    periodMonth: integer("period_month"),
    scope: text("scope").notNull().default("all"),
    recordCountsJson: text("record_counts_json").notNull(),
    checksum: text("checksum").notNull(),
    storageKey: text("storage_key"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("uq_snapshots_period_scope").on(table.periodYear, table.periodMonth, table.scope)],
);

export const userRoles = sqliteTable(
  "user_roles",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    email: text("email"),
    role: text("role").notNull(),
    organizationScope: text("organization_scope"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("uq_user_roles_user_scope").on(table.userId, table.role, table.organizationScope),
    index("idx_user_roles_email").on(table.email),
  ],
);
